Fix #20292: yii\web\Session should not set cookie params, when useCookies is false
Upgrading from PHP 8.3.7 to 8.3.14 breaks yii\web\Session when used with useCookies = false.

Error: Session cookies cannot be used when session.use_cookies is disabled.